version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=translator
      - POSTGRES_USER=translator
      - POSTGRES_PASSWORD=translator
    ports:
      - "5430:5432"

  # Сервис для разворачивания контейнера с приложением
  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/translator
      - POSTGRES_USER=translator
      - POSTGRES_PASSWORD=translator
      - YANDEX_TOKEN=${YANDEX_TOKEN}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: curl http://localhost:8080 || exit 0
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
